
<h2>v3.17.2</h2>
<ul>
  <li>
    <p>Compatibility with Ruby 2.4.0-preview3</p>
    <p>The Ruby agent has been updated to work on Ruby 2.4.0-preview3.</p>
  </li>
  <li>
    <p>Early Access Sinatra 2.0 instrumentation</p>
    <p>Our Sinatra instrumentation has been updated to work with Sinatra 2.0.0.beta2.</p>
  </li>
  <li>
    <p>Include controller instrumentation module in Rails 5 API</p>
    <p>The agent now includes the ControllerInstrumentation module into ActionController::API. This gives Rails API controllers access to helper methods like <code>newrelic_ignore</code> in support of the existing event-subscription-based action instrumentation. Thanks Andreas Thurn for the contribution!</p>
  </li>
  <li>
    <p>Use Module#prepend for ActiveRecord 5 Instrumentation</p>
    <p>Rails 5 deprecated the use of <code>alias_method_chain</code> in favor of using <code>Module#prepend</code>. Mixing <code>Module#prepend</code> and <code>alias_method_chain</code> can lead to a SystemStackError when an <code>alias_method_chain</code> is applied after a module has been prepended. This should ensure better compatibility between our ActiveRecord Instrumentation and other third party gems that modify ActiveRecord using <code>Module#prepend</code>.</p>
  </li>
  <li>
    <p>Use license key passed in to NewRelic::Agent.manual_start</p>
    <p>Previously, the license key passed in when manually starting the agent with NewRelic::Agent.manual_start was not referenced when setting up the connection to report data to New Relic. This is now fixed.</p>
  </li>
  <li>
    <p>Account for DataMapper database connection errors</p>
    <p>Our DataMapper instrumentation traces instances of DataObjects::SQLError being raised and removes the password from the URI attribute. However, when DataObjects cannot connect to the database (ex: could not resolve host), it will raise a DataObjects::ConnectionError. This inherits from DataObjects::SQLError but has <code>nil</code> for its URI attribute, since no connection has been made yet. To avoid the password check here on <code>nil</code>, the agent catches and re-raises any instances of DataObjects::ConnectionError explicitly. Thanks Postmodern for this contribution!</p>
  </li>
  <li>
    <p>Account for request methods that require arguments</p>
    <p>When tracing a transaction, the agent tries to get the request object from a controller if it wasn't explicitly passed in. However, this posed problems in non-controller transactions with their own <code>request</code> methods defined that required arguments, such as in Resque jobs. This is now fixed.</p>
  </li>
</ul>
