
<h2>Notes</h2>
<p>This release of the Python agent adds support for Python 3.9 and includes bug fixes.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from the New Relic <a href="http://download.newrelic.com/python_agent/release">download site</a>.</p>
<h2>Bug Fixes</h2>
<ul>
  <li>
    <p><strong>Duplicate warnings were logged repeatedly when using the agent with Python 3</strong></p>
    <p>The agent internally suppressed any warnings generated when data was sent via HTTP to New Relic in a way that caused the warning filters to mutate. This caused the cache of already printed warnings to be cleared, resulting in duplicate warnings after every data harvest. The agent no longer mutates the process warning filters on a background thread, resulting in consistent warning behavior.</p>
  </li>
  <li>
    <p><strong>AttributeError when passing an inactive transaction into ExternalTrace.generate_request_headers</strong></p>
    <p>When passing an inactive transaction into ExternalTrace.generate_request_headers, an AttributeError was generated. This agent version contains additional validation for the transaction argument in ExternalTrace.generate_request_headers.</p>
  </li>
  <li>
    <p><strong>The infinite tracing host configuration value did not have sufficient validation</strong></p>
    <p>When passing a URL or other invalid host to the infinite tracing host configuration, the agent accepted this value unchecked to use in the host parameter for later connections via grpc. The agent now validates this configuration and attempts to correct for invalid hosts if it is able to detect the host. If a host is not detected, the agent automatically falls back to infinite tracing disabled and logs an error.</p>
  </li>
</ul>
