
<h3>Notes</h3>
<p>This release of the Python agent is a hotfix release to address a problem where the agent could fail to validate the SSL certificate of the New Relic collector in some environments.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from our <a href="http://download.newrelic.com/python_agent/release/">download site</a>.</p>
<p>For a list of known issues with the Python agent, see <a href="https://docs.newrelic.com/docs/python/status-of-python-agent">Status of the Python agent</a>.</p>
<h3>Bug Fix</h3>
<p>If the Python agent was used in an environment where the <code>certifi</code> package was installed, the Python agent would use the <code>certifi</code> CA certificates bundle to validate the certificate of the New Relic collector. However, the latest release of <code>certifi</code> (November 20, 2015) removed some older CA certificates with 1024-bit keys.</p>
<p>The SSL certificate for the New Relic collector is cross-signed with both a 1024-bit certificate and a 2048-bit certificate, but in some circumstances, the stronger root certificate was not used for validation. When the 1024-bit certificate was no longer included in the <code>certifi</code> bundle, SSL validation would fail. Affected customers would see warnings in their agent log stating "Data collector is not contactable" due to an <code>SSLError</code>.</p>
<p>To address this issue, the agent no longer uses the <code>certifi</code> CA certificates bundle, nor the certificates bundled with <code>requests</code>. Instead, it only uses the CA bundle included with the agent to validate the New Relic collector certificate.</p>
