
<h2>Problem</h2>
<p>New Relic's .NET agent reports handled errors as though they are standard errors. This is most common with Azure worker roles, console apps, async work, and similar operations.</p>
<h2>Solution</h2>
<p>To avoid false error reports, instrument a method that directly or indirectly contains the exception handler. Instrument the target method by defining a <a href="/docs/agents/net-agent/custom-instrumentation/introduction-net-custom-instrumentation">custom instrumentation</a> file, or by wrapping the method in a <a href="/docs/agents/net-agent/custom-instrumentation/create-transactions-xml-net">custom transaction</a>, as shown in this example:</p>
<div data-component="CollapserGroup" data-prop="W10=">
  <div data-component="Collapser" data-prop="W3sidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJpZCIsInZhbHVlIjoiZ2V0LXJlc3BvbnNlLWJsb2NrIn0seyJ0eXBlIjoibWR4QXR0cmlidXRlIiwibmFtZSI6InRpdGxlIiwidmFsdWUiOiJHZXRSZXNwb25zZSgpIHRocm93cyBhbiBlcnJvciJ9XQ==">
    <div data-prop-text="title">GetResponse() throws an error</div>
    <p>In this example, New Relic reports an error from <code>GetResponse()</code> <strong>unless</strong> the method <code>Foo()</code> is instrumented. As long is <code>Foo</code> is instrumented, New Relic begins a transaction when <code>Foo</code> is called and ends the transaction when <code>Foo</code> ends.</p>
    <p>Because the error is handled before <code>Foo</code> ends, New Relic will not report an error. Note also that <code>GetResponse()</code> becomes a segment of the <code>Foo</code> transaction.</p>
    <pre><code>using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Net;
using System.IO;

namespace ErrorTester
{
    class Program
    {
        static void Main(string[] args)
        {
            var i = 0;
            while (true)
            {
                Foo(++i);
            }
        }
        static void Foo(int i)
        {
                try
                {
                    GetNotFound();
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Got it " + i + "!");
                    Thread.Sleep(1000);
                }

        }
        static string GetNotFound()
        {
            string uri = "http://localhost/Test/this/is/not/a/real/page";
            var request = (HttpWebRequest)WebRequest.Create(uri);
            var response = request.GetResponse();
            var data = new StreamReader(response.GetResponseStream()).ReadToEnd();
            response.Close();
            return data;
        }
    }
}

</code></pre>
  </div>
  <div data-component="Collapser" data-prop="W3sidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJpZCIsInZhbHVlIjoiY3VzdG9tLWluc3RydW1lbnRhdGlvbiJ9LHsidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJ0aXRsZSIsInZhbHVlIjoiRGVmaW5lIGEgY3VzdG9tIGluc3RydW1lbnRhdGlvbiBmaWxlIn1d">
    <div data-prop-text="title">Define a custom instrumentation file</div>
    <p>To instrument <code>Foo</code>:</p>
    <ol>
      <li>
        <p>Define a <a href="/docs/agents/net-agent/custom-instrumentation/introduction-net-custom-instrumentation">custom instrumentation file</a>; for example, <code>CustomInstrumentation.xml</code>:</p>
        <pre><code>&#x3C;?xml version="1.0" encoding="utf-8"?>
&#x3C;!-- Copyright (c) 2008-2014 New Relic, Inc. All rights reserved. -->
&#x3C;!--
    When you edit this file, please use an XML aware editor (such as Visual Studio),
    and pair with the companion file extension.xsd to minimize the
    chance of introducing typos that may confuse the agent when it is run.
-->
&#x3C;extension xmlns="urn:newrelic-extension">
  &#x3C;instrumentation>
    &#x3C;tracerFactory >
      &#x3C;match assemblyName="ErrorTester" className="ErrorTester.Program">
        &#x3C;exactMethodMatcher methodName="Foo" /> 
      &#x3C;/match>
    &#x3C;/tracerFactory>
  &#x3C;/instrumentation>
&#x3C;/extension>
</code></pre>
      </li>
      <li>
        <p>Place <code>CustomInstrumenation.xml</code> in the New Relic extensions folder, alongside <code>CoreInstrumentation.xml</code>, and restart your application.</p>
      </li>
    </ol>
  </div>
  <div data-component="Collapser" data-prop="W3sidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJpZCIsInZhbHVlIjoiY3VzdG9tLXRyYW5zYWN0aW9uIn0seyJ0eXBlIjoibWR4QXR0cmlidXRlIiwibmFtZSI6InRpdGxlIiwidmFsdWUiOiJXcmFwIHRoZSBtZXRob2QgaW4gYSBjdXN0b20gdHJhbnNhY3Rpb24ifV0=">
    <div data-prop-text="title">Wrap the method in a custom transaction</div>
    <p>To instrument <code>Foo</code>, wrap it in a <a href="/docs/agents/net-agent/custom-instrumentation/create-transactions-xml-net">custom transaction</a>:</p>
    <pre><code>&#x3C;extension xmlns="urn:newrelic-extension">
  &#x3C;instrumentation>
     &#x3C;tracerFactory name="NewRelic.Agent.Core.Tracer.Factories.BackgroundThreadTracerFactory" metricName="Background/Task">
       &#x3C;match assemblyName="ErrorTester" className="ErrorTester.Program">
         &#x3C;exactMethodMatcher methodName="Foo" />
       &#x3C;/match>
    &#x3C;/tracerFactory>
  &#x3C;/instrumentation>
&#x3C;/extension>

</code></pre>
  </div>
</div>
<h2>Cause</h2>
<p>The only errors New Relic's .NET agent reports are unhandled errors that end a transaction. If your app calls an exception handler before the transaction ends, New Relic will not report an error.</p>
<p>However, New Relic does not always detect exception handlers when the error occurs outside of a web transaction, WCF transaction, or custom transaction. This is because the agent creates "mini-transactions" for instrumented methods that are not associated with a transaction.</p>
<p>When the instrumented method exits, the mini-transaction ends. If the mini-transaction throws an error and the instrumented method does not handle it, then New Relic will report an error.</p>
<p>You can see this in a console app that calls <code>GetResponse()</code>, as shown in the <a href="#get-response-block">example</a>. If <code>GetResponse</code> throws an error, then New Relic will report it, even though <code>GetResponse()</code> is called within a try/catch block. The agent reports an error because the <code>GetResponse()</code> "mini-transaction" ended and the error was still unhandled on transaction exit.</p>
